name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-versions:
    name: lookup go versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
      latest: ${{ steps.versions.outputs.latest }}
    steps:
      - uses: actions/checkout@v3
      - uses: arnested/go-version-action@v1.1.13
        id: versions

  docker:
    runs-on: ubuntu-latest
    needs: go-versions
    strategy:
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: builder.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:go${{ matrix.go-version }}-builder
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GO_VERSION=${{ matrix.go-version }}
      - name: write args to devcontainer config
        run: |
          jq '.build.args += { "GO_VERSION": "${{ matrix.go-version }}", "REPOSITORY": "${{ github.repository }}" }' .github/.devcontainer/devcontainer.json > .github/.devcontainer/devcontainer.json
          cat .github/.devcontainer/devcontainer.json
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ghcr.io/${{ github.repository }}
          imageTag: go${{ matrix.version }}-devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}
          push: always

  pba:
    runs-on: ubuntu-latest
    needs:
      - go-versions
      - docker
    container:
      image: ghcr.io/${{ github.repository }}:${needs.go-versions.outputs.latest}-builder
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: make image
        run: make
      - name: calculate sha256sum
        run: sha256sum elx-pba-x86_64.img | tee SHA256SUMS
      - name: save image file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pba
          path: |
            elx-pba-x86_64.img
            SHA256SUMS
