name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-versions:
    name: lookup go versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
      latest: ${{ steps.versions.outputs.latest }}
    steps:
      - uses: actions/checkout@v4
      - uses: arnested/go-version-action@v1.1.20
        id: versions

  docker:
    concurrency:
      group: docker-go${{ matrix.go-version }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    needs: go-versions
    strategy:
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build Docker image
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          file: builder.dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository }}:go${{ matrix.go-version }}-builder
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GO_VERSION=${{ matrix.go-version }}

  devcontainer:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    concurrency:
      group: devcontainer-go${{ matrix.go-version }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    needs:
      - go-versions
      - docker
    strategy:
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: write args to devcontainer config
        run: |
          cd ./.github/.devcontainer
          mv devcontainer.json devcontainer.json.bak
          jq '.build.args += { "GO_VERSION": "${{ matrix.go-version }}", "REPOSITORY": "${{ github.repository }}" }' devcontainer.json.bak > devcontainer.json
          cat devcontainer.json
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ghcr.io/${{ github.repository }}
          imageTag: go${{ matrix.go-version }}-devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}
          push: always

  pba:
    name: build ${{ matrix.tag }} pba with ${{ matrix.hash }}
    strategy:
      matrix:
        tag:
          - reboot
          - kexec
        hash:
          - sha512
          - dta
    runs-on: ubuntu-latest
    needs:
      - go-versions
      - docker
    container:
      image: ghcr.io/${{ github.repository }}:go${{ needs.go-versions.outputs.latest }}-builder
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: make image
        run: make UROOT_FLAGS="-tags ${{ matrix.tag }},${{ matrix.hash }}"
      - name: calculate sha256sum for both images
        run: |
          make checksum
      - name: save image file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pba-${{ matrix.tag }}-${{ matrix.hash }}
          path: |
            elx-pba-x86_64.img
            SHA256SUMS
